//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public decimal p_price { get; set; }
        public string p_des { get; set; }
    }
}
